### ISSUE TITLE
coffeescript example

### ISSUE THREAD

**Issue by memon** [thelinuxlich/knockout.model#3]
i am trying to use knockout.model with coffeescript and it's class system.

is it possible?
are there any examples available?

**Comment by thelinuxlich** [comment]
I´ve ditched Coffeescript class system, you should use it like the example

**Comment by neverfox** [comment]
May I ask why? Was it just a matter of preference or more universal support, or did it not work correctly in that form? I ask because I might be interested in forking this and rolling it back to the Coffeescript version for my use (adding the few changes that have been made since). But if it's a matter of simply being unworkable in that form, I won't bother.

**Comment by thelinuxlich** [comment]
It worked, but there was two reasons for moving the project back to Javascript:
- The community was always telling me that it would be much more easy to use if it didn´t need coffeescript as a dependence, and they were right.
- The coffeescript class implementation is freaking slow. Analyze the code it generates and the code I use here and you will see.

**Comment by neverfox** [comment]
Thanks for the reply.
